### ISSUE TITLE
update() is failing

### ISSUE THREAD

**Issue by bclinkinbeard** [mapbox/hubdb#12]
I've traced the problem back to the `getSha()` method in `github-api`, but I assume I have to be doing something wrong. The GET call being made is returning a 404 error any time the path already exists. Any ideas?

```js
var Hubdb = require('hubdb');

var db = Hubdb({
  token: myToken,
  username: 'bclinkinbeard',
  repo: 'hubdb-sandbox',
  branch: 'db'
});

db.update('e1e4bb12331eec3e5f2c7a62fb09d87e.json', {
  foo: 'bar'
}, function (err, res) {
  if (err) console.error(err);
  if (res) console.log('updated!');
})
```

**Comment by tmcw** [comment]
Hm - so I'm planning on switching the backend to octokat soon - I'll keep track of this as an upstream bug.

**Comment by tmcw** [comment]
:+1: merged the octokat branch, this should be fixed and works in my tests.

**Comment by bclinkinbeard** [comment]
Works for me too, thanks!
