### ISSUE TITLE
use blob api

### ISSUE THREAD

**Issue by tmcw** [mapbox/hubdb#15]
This will enable access of much larger data to pull & push to github. octokat has the api, we need to use it and do commits the hard way.

**Comment by mikemorris** [comment]
This is totally The Hard Way™, suggest avoiding if possible, responsible for bugs like https://github.com/prose/prose/issues/148

**Comment by michaelsteffen** [comment]
@mikemorris - @bsudekum and I are playing with using hubdb to read and write geojson data, which requires the larger size limits. Is there another way?

**Comment by mikemorris** [comment]
Oops, got mixed up between Git Data Blob API and Git Data Tree API. Tree is the nasty one, blobs should be fine.

**Comment by michaelsteffen** [comment]
I think we have to use both, unfortunately. The blob API requires a SHA. Other than the Tree API the only way I see to get a SHA from a file name is the repo/content API, which errors out for large files (b/c it tries to return the file content too).  I'd love to be wrong about this . . .

**Comment by mikemorris** [comment]
Ah, looks like I was actually using the Tree API to populate a [Files collection](https://github.com/prose/prose/blob/master/app/collections/files.js#L300). The hard part is trying to `POST` or `PATCH` trees (as opposed to files or blobs), `GET`ing trees doesn't actually look too bad. Sorry my memory is a little fuzzy, been a while since I've touched this stuff.

**Comment by michaelsteffen** [comment]
@mikemorris No, this is great, appreciate the advice. @tmcw I'm going to try to find some time to work on this over the weekend, so self-assigning for now.  I may throw it back out to the world if I haven't managed it by Monday.

**Comment by gmaclennan** [comment]
This might be useful: [gmaclennan/hubfs.js](https://github.com/gmaclennan/hubfs.js)

I [had problems](https://github.com/michael/github/issues/147) with github.js when it started using repo.contents but I wanted a similar higher-level wrapper that could deal simply with files < 1Mb and use The Hard Way™ for larger files.
