### ISSUE TITLE
switch from michael/github to octokat

### ISSUE THREAD

**Issue by tmcw** [mapbox/hubdb#8]
would love to find something tested, minimal, and so on.

**Comment by mikemorris** [comment]
From https://developer.github.com/libraries/
- https://github.com/mikedeboer/node-github
- https://github.com/pksunkara/octonode
- https://github.com/k33g/gh3
- https://github.com/philschatz/octokat.js

I remember at least one of those being well-tested, as I was looking for a replacement library for Prose, but eventually just dropped it completely and tied the API directly to Backbone.

Somewhat unrelated, but it looks like @ingalls got commit access to [michael/github](https://github.com/michael/github) at some point and has been doing work maintaining it?

**Comment by tmcw** [comment]
https://github.com/philschatz/octokit.js looks solid and has the @ingalls stamp of approval

**Comment by tmcw** [comment]
https://github.com/philschatz/octokat.js

**Comment by tmcw** [comment]
Using ??"coffeescript modules"?? is even worse than I remembered.

**Comment by tmcw** [comment]
Done in 8a0522061c3a23670bf20ee4e0adff1f0ece7c3a
